config/routes.rb
Rails.application.routes.draw do


  
  root to: 'welcome#welcome'
  get 'about_us', to: 'welcome#about_us'
  get 'terms_of_service', to: 'welcome#terms_of_service'
  get 'privacy', to: 'welcome#privacy'
  get 'legal', to: 'welcome#legal'
  get 'glossary', to: 'glossary#index'
  get 'query_affiliation', to: 'groups#query_affiliation'
  get 'media', to: 'buffers#media'

  resources :charts

  devise_for :users, controllers: {
        registrations: "registrations",
      }, :path_prefix => 'my'

  resources :users, only: [:show] do
    member do
      get :datasets
      get :revisions
      get :interactions
    end
    collection do
      get :query_orcid
      post :orcid_modal
    end
  end

  resources :groups do
    member do
      get :interactions
      get :datasets
    end
    collection do
      get :query
    end
  end

  resources :assignments do
    member do
      get :confirm_group
      get :decline_group
    end
  end

  get 'additives/new', to: redirect('additives')
  get 'solvents/new', to: redirect('solvents')
  resources :additives, :solvents, only: [:index, :show, :edit, :update] do
    member do
      get :interactions
      get :pubchem_update_query
    end
    collection do
      get :pubchem_request
      get :pubchem_full_record
      get :pubchem_update #no controller action yet
      get :cid_request
      get :pubchem_help
      get :search
      get :dbsearch
      get :query
    end
  end

  resources :frameworks do
    member do
      get :preview
    end
    collection do
      get :query
    end
  end
  resources :molecules do
    member do
      get :interactions
      get :pubchem_auto_update
      get :pubchem_update_query
      patch :update_framework_molecule
    end
    collection do
      get :new_framework
      get :new_molecule
      post :create_framework_molecule
      put :pubchem_update
      get :pubchem_request
      get :pubchem_full_record
      get :cid_request
      get :pubchem_help
      get :pdb_help
      get :framework_help
      get :framework_dbsearch
      get :pdb_id_request
      get :pdb_full_record
      get :search
      get :editorsearch
      get :dbsearch
      get :pogresearch
      get :query
      get :smilesquery
      get :query_tags
      get :external_services
      get :tag_cloud
      get :listing
      get :chemeditor
      get :edit_comment
    end
  end

  resources :buffers do
    member do
      get :interactions
    end
    collection do
      get :query
      get :buffer_check
      get :dbsearch
      get :listing
    end
  end
  

  resources :interactions do
    member do
      post :reviewer_comments
      post :duplicate
      put :accident
      get :citation_export
      get :hg_sim_data
      put :self_acceptance
    end
    collection do
      put :publish_accepted
      put :update_reviewers
      get :advsearch
      get :intsearch
      get :dbsearch
      get :advanced_search
      get :query_technique
      get :query_assay_type
      get :query_itc_instruments
    end
  end

  resources :creators, :contributors, only: [] do
    collection do
      post :orcid_modal
      get :query
    end
  end

  resources :datasets do
    collection do
      post :preview_modal
      put :add_interactions
      put :update_state
      put :update_dataset_interactions_dois
      put :remove_interactions
      get :list_all_possible_interactions
      get :citation_query
      get :query_user_datasets_editable
      get :query_datasets
      get :query_cooperators
      get :advsearch
      get :query_subjects
    end

    member do
      put :self_revision_temp
      get :preview
      get :dataset_csv_export
      get :interaction_addition
      get :citation_export
    end
  end

  resources :related_identifiers, only: [] do
    member do
      get :citation_export
    end
  end

  resources :dataset_related_identifiers, only: [] do
    collection do
      get :primary_reference_doi_query
    end
  end



end

app/controllers/molecules_controller.rb
class MoleculesController < ApplicationController
  before_action :set_molecule, only: [:show, :edit, :update, :destroy, :pubchem_update_query, :pubchem_auto_update, :update_framework_molecule]
  before_action :set_interactions, only: [:interactions]
  before_action :set_meta_data
  before_action :authenticate_user!, except: [:tags, :show, :index, :listing, :dbsearch, :interactions, :query, :query_tags, :chemeditor, :edit_comment, :editorsearch, :smilesquery]
  before_action :sole_molecule, only: [:destroy]

include Suprababel
include PDB
include Pubchem
include Colors

  def pubchem_update_query
    array = @molecule.entry_update
    logger.debug array
    unless array.empty?
      results = @molecule.preliminary_update_request(array[0..9])
    else
      results = [["nothing found"]]
    end
    render json: results
  end

  def pubchem_auto_update
    @molecule.auto_update
    #redirect_to molecule_path(@molecule)
    render js: "window.location='#{molecule_path(@molecule).to_s}'"
  end

  def pubchem_update
    logger.debug "action fired"
    logger.debug "params: #{params}"

    if params[:selection_cid].present?
      id = params[:molecule_id].to_i
      cid = params[:selection_cid].to_i
      logger.debug "cid: #{cid}, id: #{id}"
      @molecule = Molecule.find(params[:molecule_id].to_i)
      @molecule.cid = params[:selection_cid].to_i
      @molecule.full_data(@molecule.cid)
      @molecule.clip_png
      @molecule.add_names
      @molecule.add_cas
      @molecule.save
    end
    redirect_to molecule_path(params[:molecule_id])
  end


  def smilesquery
      regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
      regexresult = Molecule.order(:display_name).where({ iso_smiles: URI.encode(params[:term].upcase) })
      result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
      array = result.map{|n| [n.preferred_abbreviation , n.display_name, n.png_url, n.molecular_weight, n.id, n.iso_smiles]}
      render json: array.sort_by{|word| word[1].length }[0..5]
  end

  def query
      regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
      regexresult = Molecule.select(:preferred_abbreviation, :display_name, :molecular_weight, :png_url, :molecule_type).order(:display_name).where("display_name ILIKE ? OR preferred_abbreviation ILIKE ?", "%#{params[:term]}%", "%#{params[:term]}%")
      result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
      array = result.map{|n| [n.preferred_abbreviation , n.display_name, n.png_url.present? ? n.png_url : "/images/thumb/missing.png", n.molecular_weight, n.molecule_type]}
      render json: array.sort_by{|word| word[1].length }[0..5]
  end


  def query_tags
    #tags = ActsAsTaggableOn::Tag.where("name ILIKE ?", "%#{params[:q]}%")
    tags = ActsAsTaggableOn::Tag.includes(:taggings).where(taggings: {context: "tags"}).where("name ILIKE ?", "%#{params[:q]}%")
    #only tags that are tagged to a molecule (in use) are searched
    render json: tags
  end

  def interactions

  end

  def chemeditor

  end

  def tag_cloud
    authorize Molecule, :editor_or_admin?
    @tags = Molecule.tag_counts_on(:tags)
  end


  def edit_comment
    @comment = params[:molefile]
    flash.now[:warning] = "Nothing found in database Molecules #{params[:molefile]}"
    hash_data = { "Jane Doe" => 10, "Jim Doe" => 6 , "Param" => params[:molefile]}
    molfile = "CWRITER308281317412D\nCreated with ChemWriter - http://chemwriter.com\n  2  1  0  0  0  0  0  0  0  0999 V2000\n   67.4074  -47.2503    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   76.0677  -42.2503    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0\nM  END"
    info_hash = molecule_info_from_molfile(params[:molefile])
    json_data = info_hash.to_json
    render json: json_data
  end


  def hg_sim_data
    base = (0..100).to_a.map{|element| element*0.01}
    c1 = 20./@interaction.binding_constant
    c2 = 2*c1
    ka = @interaction.binding_constant
    x = base.map{|element| element*c2}
    y = x.map{|element| (c1+element+1/ka)/2-Math.sqrt(((c1+element+1/ka)*(c1+element+1/ka))/4-c1*element)}

    sol = x.zip(y).to_h
    xy_data = Hash["jsonarray",sol.map{|x,y| {"x" => x, "y" => y}}].to_json
    #xy_data for chart.js and sol for chartkick

    render json: xy_data
  end

  def external_services
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def pubchem_help
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def pdb_help
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def framework_help
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def pdb_id_request
    if params[:pdb_id].blank?
      flash.now[:warning] = 'You need to put some PDB ID'
      render partial: 'dbresult'
    else
      unless protein_presence?(params[:pdb_id])
        if valid_pdb_id?(params[:pdb_id])
          @molecule = Molecule.new(preliminary_pdb_data(params[:pdb_id]))
        else
          hash = preliminary_pdb_data(params[:pdb_id])
          case hash[:status]
          when 404
            flash.now[:danger] = "We could not find anything, please verify PDB ID."
          when 500
            flash.now[:danger] = "We are sorry the service is currently unavailable."
          end
        end
        render partial: "molecules/pdb/pdb_preliminary_result"
      else
        @molecule=Molecule.find_by_pdb_id(params[:pdb_id])
        @molecule=Molecule.where("lower(pdb_id) = ?", params[:pdb_id].downcase).first
        flash.now[:success] = "The molecule exists already in the SupraBank"
        render partial: 'molecules/found_result'
      end
    end
  end

  def pubchem_request
    if params[:molecule].blank?
      flash.now[:warning] = 'You need to put some search string'
      render partial: 'dbresult'
    else
      @molecule = Molecule.new
      @molecule.preliminary_data params[:molecule]
      if @molecule.molecule_presence(@molecule.cid)
        @molecule=Molecule.find_by_cid(@molecule.cid)
        flash.now[:success] = "The molecule exists already in the SupraBank."
        render partial: 'molecules/found_result'
      elsif @molecule.cid.present?
        flash.now[:success] = "The molecule is present on PubChem, but not yet at SupraBank, you can retrieve it!"
        render partial: "molecules/preliminary_result"
      else
        flash.now[:warning] = 'Unfortunately, we could not find anything on PubChem. Please first check directly on PubChem for the name and the CID and use here afterwards the "Use CID Instead" option on the right. If the substance is not listed on PubChem, you can create a custom molecule on SupraBank:'
        render partial: "molecules/nothing_found"
      end
    end
  end



  def cid_request
    if params[:request_cid].blank?
      flash.now[:warning] = 'You need to put the PubChem Compound ID (CID)'
      render partial: 'dbresult'
    else
      unless molecule_presence(params[:request_cid])
        @molecule = Molecule.new
        @molecule.preliminary_cid_data params[:request_cid]
        render partial: "molecules/preliminary_result"
      else
        @molecule=Molecule.find_by_cid params[:request_cid]
        flash.now[:success] = "The molecule exists already in the SupraBank"
        render partial: 'molecules/found_result'
      end
    end
  end

  def pdb_full_record
    unless protein_presence?(params[:pdb_id])
      @molecule = Molecule.new(pdb_summary_data(params[:pdb_id]))
      @molecule.display_name = @molecule.pdb_descriptor
      @molecule.preferred_abbreviation = @molecule.display_name
      @molecule.tag_list.add("protein")
      @molecule.clip_protein_png
      @message = "Your molecule was successfully added to the SupraBank"
    else
      @molecule=Molecule.find_by_pdb_id(params[:pdb_id])
      flash.now[:success] = "The molecule exists already in the SupraBank"
    end

    respond_to do |format|
      format.js
    end
  end

  def pubchem_full_record
    @molecule = Molecule.new(cid: params[:cid])
    unless @molecule.molecule_presence(@molecule.cid)
      @molecule.user = current_user
      @molecule.full_data params[:cid]
      @molecule.clip_png
      @molecule.add_names
      @molecule.add_cas
      @molecule.save
      @message = "Your molecule was successfully added to the SupraBank"
    else
      @molecule=Molecule.find_by_cid(params[:cid])
      @message = "The molecule exists already in the SupraBank"
    end

    respond_to do |format|
      format.js
    end
  end


  def listing
    
    @molecules = policy_scope(Molecule).select(:id, :cid, :display_name, :preferred_abbreviation, :molecular_weight, :inchistring, :inchikey, :cano_smiles, :iso_smiles, :interactions_count, :updated_at, :created_at, :png_url)

  end

  def destroy
    authorize @molecule
    @molecule.destroy
    respond_to do |format|
      format.html { redirect_to molecules_path, notice: 'Molecule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def search
    if params[:molecule].blank?
      flash.now[:warning] = 'You need to put some search string'
    else
      @molecule = Molecule.new_from_name(params[:molecule])

      if @molecule.present?
        if @molecule == "exist"
          @molecule = Molecule.dbsearch(params[:molecule]).first
          flash.now[:success] = 'Molecule is already present in the SupraBank'
        else
          @molecule.user = current_user
          @molecule.save
          flash.now[:success] = 'Molecule was added successfully to the SupraBank'
        end
      else
        flash.now[:warning] = 'Nothing found by Name at PubChem. You may try with the CAS number?'
      end
    end
    render partial: 'molecules/result'
  end



  def dbsearch
      if params[:search_param].blank? && params[:tags_param].blank?
        flash.now[:warning] = 'You need to put some content'
        render partial: 'dbresult'
      else

app/helpers/molecules_helper.rb
module MoleculesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/molecules/_form_pubchem.html.erb
<%= form_for @molecule, :html => { :class => "form-horizontal molecule" } do |f| %>

  <% if @molecule.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@molecule.errors.count, "error") %> prohibited this molecule from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @molecule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div class="container col-md-8">
   <div class="form-group">
       <div class="col-md-4">
        <%= f.label :display_name, :class => 'control-label form-label' %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :display_name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:display_name) %>
  </div>

  <div class="form-group">
     <div class="col-md-4">
    <%= f.label :preferred_abbreviation, :class => 'control-label form-label' %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :preferred_abbreviation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:preferred_abbreviation) %>
  </div>

  <div class="form-group">
     <div class="col-md-4">
       <%= f.label :cas,"CAS", :class => 'control-label form-label' %>
     </div>
     <div class="col-md-8">
      <%= f.text_field :cas, :class => 'form-control' %>
     </div>
     <%=f.error_span(:cas) %>
  </div>

  <div class="form-group">
     <div class="col-md-4">
       <%= f.label :tag_list,"Tags", :class => 'control-label form-label' %>
     </div>
     <div class="col-md-8">
       <%= f.text_field :tag_list, value:nil, :class => 'form-control' , id: "tag_tokens", data: {load: @molecule.tag_counts.to_json}%>
     </div>
  </div>
</div>

<div class="container col-md-4">
  <div class="col-md-12">
      <label class="btn btn-primary btn-change-avatar  login_button"  style="margin-bottom: 30px;">
        Upload new structure
        <span style="display:none;">
          <%= f.file_field :png, id: "fileUploader", accept: 'image/png, image/gif, image/jpeg'%>
        </span>
      </label>
  </div>

  <div class="col-md-12">
        <%= image_tag @molecule.png_url, alt:"Structure", id:"instant_image", class:"img-rounded instant-image"%>
  </div>

  <div class="col-md-12">
      <label class="btn btn-primary btn-change-avatar login_button"  style="margin-top: 30px;">
        Upload ChemDraw File
        <span style="display:none;">
          <%= f.file_field :cdx, id: "cdxUploader", accept: 'chemical/x-cdx, image/x-coreldraw, chemical/x-chem3d' %>
        </span>
      </label>
  </div>

  <div class="col-md-12">
        <% if @molecule.cdx.present? %>
          <%= link_to "Download CDX", @molecule.cdx.url , :class => 'btn btn-default login_button'%>
        <% end %>
        <%#= image_tag @molecule.cdx.url, alt:"Structure", id:"instant_cdx", class:"img-rounded instant-image"%>
        <p class="" id="instant_cdx"></p>
  </div>
</div>

<div class="container col-md-12">
<hr>
</div>


<div class="container col-md-12">
  <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary login_button' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                molecules_path, :class => 'btn btn-default  select_button' %>
  </div>
</div>


<div class="container col-md-12">
<hr>
</div>


<div class="container col-md-12">
  <div class="panel-default panel">
      <div class="panel-heading">
        <h4>Synonyms</h4>
      </div>
      <div class="panel-body ">
        <div class="container">
                  <% @molecule.names.each do |element| %>
                  <ul class="list-inline ul-names">
                    <li class="li-names"><strong><%= element %></strong></li>
                  </ul>
                  <% end %>
        </div>
      </div>

    </div>
</div>



<% end %>




<script type="text/javascript">

$("#fileUploader").change(function(){
    readURL(this);
});



$("#cdxUploader").change(function(e){

            var fileName = e.target.files[0].name;

            $('#instant_cdx').text('The file "' + fileName +  '" has been selected.');

        });




  $(document).ready(function () {
      $("#tag_tokens").tokenInput("/molecules/query_tags.json", {
              theme: "facebook",
              placeholder: 'e.g. dye, hormone, macrocycle (separated, by, commas)',
              tokenValue: "name",
              allowFreeTagging: true,
              allowCreation: true,
              creationText: 'Add new element',
              hintText: 'Enter new tags by typing and hitting ENTER',
             prePopulate: $('#tag_tokens').data('load')
            });

  });


</script>

app/views/molecules/_nothing_found.html.erb
<% if params[:action] == 'pubchem_request' %>
<div class="container-flex">
  <div class="row">
    <div class="col-sm-9">
      <%= bootstrap_flash %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Create a custom Molecule", new_molecule_molecules_path, class:"btn btn-success btn-lg"  %>
    </div>
  </div>
</div>
<% end %>

app/views/molecules/_preliminary_result.html.erb
<% if params[:action] == 'pubchem_request' %>
<div class="container-flex">
  <div class="row">
    <div class="col-sm-9">
      <%= bootstrap_flash %>
    </div>
  </div>
</div>
<% end %>

<% if @molecule  %>
<hr>
    <div class="container-flex col-md-12" id="preliminary_result">

            <div class="row">
              <h4>We have found the following molecule on
                <%= link_to (image_tag("logos/pubchem_logo.svg", size: "150x38")), @molecule.pubchem_link, target: :_blank %>
              </h4>
            </div>
            <div class="row">
              <div class="col-md-6">
                <dl>
                  <dt>CID:</dt>
                  <dd>
                    <%= @molecule.cid %>
                  </dd>
                  <dt>Molecular Weight:</dt>
                  <dd>
                    <%= @molecule.molecular_weight %> g/mol
                  </dd>
                </dl>
              </div>
              <div class="col-md-6">
                <%= image_tag  @molecule.preferred_abbreviation , size: "200x200"%>
              </div>
            </div>
            <div class="row decision-buttons">

            <p><b>Please verify if this is your desired compound.</b></p>

            <%= hidden_field_tag @molecule.id %>
            <button type="button" name="button" class="btn btn-primary" id="reject_button">No (will reject this molecule)</button>
            <%= link_to "Yes (will retrieve full record)", pubchem_full_record_molecules_path(:cid => @molecule.cid), remote: true, class:"btn btn-warning", style:"margin-right: 20px;"%>
            </div>
          </div>



<% end %>
<script type="text/javascript">
  $(function(){
    $('#reject_button').click(function(){
      $('#preliminary_result').hide()
    });
  });
</script>

app/views/molecules/_result.html.erb
<% if params[:action] == 'pubchem_request' %>
  <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <%= bootstrap_flash %>
      </div>
    </div>
  </div>
<% end %>
<% if @molecule  %>
  <div class="col-md-12 overview container">
    <h4><%= @molecule.display_name %> | SBID = <%= @molecule.id %> | <%= @molecule.molecule_type.capitalize %> |
      <% if @molecule.cid > 0  %>
        <%= link_to (image_tag("logos/pubchem_logo.svg", size: "150x38")), @molecule.pubchem_link, target: :_blank %>
      <% else %>
        <% if @molecule.molecule_type == 'protein'  %>
          <%= link_to (image_tag("logos/rcsb_logo.png", size: "150x38")), "https://www.rcsb.org/structure/#{@molecule.pdb_id}", target: :_blank %>
        <% else %>
          <span>Custom Molecule</span>
        <% end %>
      <% end %>
      <% if policy(@molecule).update? %>
        <%= link_to 'Edit', edit_molecule_path(@molecule), class:"btn btn-sm btn-default" %>
      <% end %>
      <% if policy(@molecule).destroy? %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                molecule_path(@molecule),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-sm btn-danger' %>
      <% end %>
    </h4>
    <% if @molecule.molecule_type == 'framework' %>
      <%= render 'molecules/locales/framework_locale' %>
    <% else %>
      
    
    <div class="row">
      <div class="col-md-6 col-xs-12">
        <%= render 'molecules/locales/structure', object:@molecule %>
      </div>
      <div class="col-md-6 col-xs-12">
        <% if @molecule.molecule_type == 'compound'  %>
          <%= render 'molecules/locales/molecular_properties', object:@molecule %>
        <% elsif @molecule.molecule_type == 'protein' %>
          <%= render 'molecules/locales/protein_properties', object:@molecule %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <% if @molecule.molecule_type == 'compound'  %>
          <%= render 'molecules/locales/molecular_identifiers', object:@molecule %>
        <% elsif @molecule.molecule_type == 'protein' %>
          <%= render 'molecules/locales/protein_identifiers', object:@molecule %>        
        <% end %>
      </div>
    </div>
    <% end %>
    <% if policy(@molecule).destroy? && @molecule.molecule_type == 'compound' %>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-info ">
          <div class="panel-heading">
            <%= link_to "Auto Update", {controller: "molecules", action: 'pubchem_auto_update', id: @molecule, remote:true}, class:'btn btn-md btn-success', data: {turbolinks: false} %>
            <button type="button" name="button" id="pubChemUpdate" class="btn btn-md btn-primary">Request PubChem Update</button>  Run an update for molecular data. Review the results and <strong> select </strong> the entry you think is correct!
            <%= image_tag "preloader/black_white_trans.png", size:"35x35", id:"loader", class:"pull-right"%>
          </div>
          <%= form_tag pubchem_update_molecules_path, method: :put do %>
            <table class='table' id="results_table">
              <thead>
                <tr>
                  <th>CID</th>
                  <th>PubChem</th>
                  <th>IUPAC Name</th>
                  <th>SMILES</th>
                  <th>Formula</th>
                  <th>Select</th>
                </tr>
              </thead>
              <tbody id="results_table_body">
              </tbody>
            </table>
            <%= hidden_field_tag "molecule_id", @molecule.id %>
            <div class="panel-footer panelPubChem" id="panel_footer">
              <%= submit_tag "Update this molecule" , class:"btn btn-md btn-success login_button", id:"molecule_update_button"%>
              <span> &nbsp;&nbsp;This could take a little time, SupraBank will retrieve the full record.</span> <strong id="footer_info"></strong>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
  <script type="text/javascript">
    $(function(){
      $('#loader').hide();
      var $loading = $('#loader')
      $(document)
        .ajaxStart(function () {
          $loading.show();
        })
        .ajaxStop(function () {
          $loading.hide();
        });
    
    
      $("#molecule_update_button").hide()
      $("#panel_footer").hide()
      var moleculeID = <%= @molecule.id %>
      var moleculeCID = <%= @molecule.cid %>
      function requestPubchem(){
          $.ajax({
          type: "GET",
          url: "/molecules/" + moleculeID + "/pubchem_update_query",
          success: function(data) {
          //  console.log(data)
          //  alert(data[0]);
            if (data.length > 0) {
              console.log(data)
    
              $("#results_table_body").empty()
              for (var entry of data) {
                $("#results_table_body").append("<tr><td> <a href=https://pubchem.ncbi.nlm.nih.gov/compound/" + entry[0] + " target='_blank'>" + entry[0] + "</a></td><td> <a href=https://pubchem.ncbi.nlm.nih.gov/compound/" + entry[0] + " target='_blank'>" + "Link" + "</a></td><td class='smiles-query-td-smiles'>" + entry[3] + "</td><td class='smiles-query-td-smiles'>" + entry[1] + "</td><td>" + entry[2] + "</td><td> <input type='radio' name='selection_cid' value=" + entry[0] + " /></td></tr>")
              };
              $("#molecule_update_button").show()
              $("#panel_footer").show()
              $("input[type=radio]").on('click', function(){
                if ($(this).is(':checked')) {
                  var selectionCID = parseFloat($(this).parents("tr").find("a").text())
                  if (selectionCID == moleculeCID) {
                    $(this).parents("table").find("tr").removeClass("alert alert-danger");
                    $(this).parents("tr").addClass("alert alert-success");
    
                    $("#footer_info").text("CID matches!")
                    $("#footer_info").removeClass("text-danger")
                    $("#footer_info").addClass("text-success")
                  } else {
                    $(this).parents("table").find("tr").removeClass("alert alert-danger");
                    $(this).parents("table").find("tr").removeClass("alert alert-success");
                    $(this).parents("tr").addClass("alert alert-danger");
    
                    $("#footer_info").text("CID mismatch, are you sure?")
                    $("#footer_info").removeClass("text-success")
                    $("#footer_info").addClass("text-danger")
                  }
    
                }
              });
            }
            return false;
          },
          error: function(data) {
            return false;
          }
            });
      };
    
    
      $(function(){
        $("#pubChemUpdate").on('click', function(){
          //var smiles = $(this).val();
          requestPubchem();
        });
      });
    
    });
  </script>
<% end %>

app/views/molecules/listing.html.erb
<%= render 'molecule_info' %>
<%#= render 'molecule' %>
<%= render 'compounds/compound', compounds:@molecules %>

app/views/molecules/new.html.erb
<%- model_class = Molecule -%>
<div class="page-header normalWidthOnLargeScreens">
  <h1>Create a custom Molecule or Partner</h1>
</div>

<div class="row col-md-12 normalWidthOnLargeScreens">
   <%= render 'molecules/custom/custom_compound' %>
</div>

app/views/molecules/pdb_full_record.js.erb
//$('#message').text("#{@message}");
$("#message").show()
$("#message").html("<%= escape_javascript(render partial: 'successful_retrieval', :locals => {molecule: @molecule}) %>");
$(".decision-buttons").hide();