config/routes.rb
Rails.application.routes.draw do


  
  root to: 'welcome#welcome'
  get 'about_us', to: 'welcome#about_us'
  get 'terms_of_service', to: 'welcome#terms_of_service'
  get 'privacy', to: 'welcome#privacy'
  get 'legal', to: 'welcome#legal'
  get 'glossary', to: 'glossary#index'
  get 'query_affiliation', to: 'groups#query_affiliation'
  get 'media', to: 'buffers#media'

  resources :charts

  devise_for :users, controllers: {
        registrations: "registrations",
      }, :path_prefix => 'my'

  resources :users, only: [:show] do
    member do
      get :datasets
      get :revisions
      get :interactions
    end
    collection do
      get :query_orcid
      post :orcid_modal
    end
  end

  resources :groups do
    member do
      get :interactions
      get :datasets
    end
    collection do
      get :query
    end
  end

  resources :assignments do
    member do
      get :confirm_group
      get :decline_group
    end
  end

  get 'additives/new', to: redirect('additives')
  get 'solvents/new', to: redirect('solvents')
  resources :additives, :solvents, only: [:index, :show, :edit, :update] do
    member do
      get :interactions
      get :pubchem_update_query
    end
    collection do
      get :pubchem_request
      get :pubchem_full_record
      get :pubchem_update #no controller action yet
      get :cid_request
      get :pubchem_help
      get :search
      get :dbsearch
      get :query
    end
  end

  resources :frameworks do
    member do
      get :preview
    end
    collection do
      get :query
    end
  end
  resources :molecules do
    member do
      get :interactions
      get :pubchem_auto_update
      get :pubchem_update_query
      patch :update_framework_molecule
    end
    collection do
      get :new_framework
      get :new_molecule
      post :create_framework_molecule
      put :pubchem_update
      get :pubchem_request
      get :pubchem_full_record
      get :cid_request
      get :pubchem_help
      get :pdb_help
      get :framework_help
      get :framework_dbsearch
      get :pdb_id_request
      get :pdb_full_record
      get :search
      get :editorsearch
      get :dbsearch
      get :pogresearch
      get :query
      get :smilesquery
      get :query_tags
      get :external_services
      get :tag_cloud
      get :listing
      get :chemeditor
      get :edit_comment
    end
  end

  resources :buffers do
    member do
      get :interactions
    end
    collection do
      get :query
      get :buffer_check
      get :dbsearch
      get :listing
    end
  end
  

  resources :interactions do
    member do
      post :reviewer_comments
      post :duplicate
      put :accident
      get :citation_export
      get :hg_sim_data
      put :self_acceptance
    end
    collection do
      put :publish_accepted
      put :update_reviewers
      get :advsearch
      get :intsearch
      get :dbsearch
      get :advanced_search
      get :query_technique
      get :query_assay_type
      get :query_itc_instruments
    end
  end

  resources :creators, :contributors, only: [] do
    collection do
      post :orcid_modal
      get :query
    end
  end

  resources :datasets do
    collection do
      post :preview_modal
      put :add_interactions
      put :update_state
      put :update_dataset_interactions_dois
      put :remove_interactions
      get :list_all_possible_interactions
      get :citation_query
      get :query_user_datasets_editable
      get :query_datasets
      get :query_cooperators
      get :advsearch
      get :query_subjects
    end

    member do
      put :self_revision_temp
      get :preview
      get :dataset_csv_export
      get :interaction_addition
      get :citation_export
    end
  end

  resources :related_identifiers, only: [] do
    member do
      get :citation_export
    end
  end

  resources :dataset_related_identifiers, only: [] do
    collection do
      get :primary_reference_doi_query
    end
  end



end

app/controllers/molecules_controller.rb
class MoleculesController < ApplicationController
  before_action :set_molecule, only: [:show, :edit, :update, :destroy, :pubchem_update_query, :pubchem_auto_update, :update_framework_molecule]
  before_action :set_interactions, only: [:interactions]
  before_action :set_meta_data
  before_action :authenticate_user!, except: [:tags, :show, :index, :listing, :dbsearch, :interactions, :query, :query_tags, :chemeditor, :edit_comment, :editorsearch, :smilesquery]
  before_action :sole_molecule, only: [:destroy]

include Suprababel
include PDB
include Pubchem
include Colors

  def pubchem_update_query
    array = @molecule.entry_update
    logger.debug array
    unless array.empty?
      results = @molecule.preliminary_update_request(array[0..9])
    else
      results = [["nothing found"]]
    end
    render json: results
  end

  def pubchem_auto_update
    @molecule.auto_update
    #redirect_to molecule_path(@molecule)
    render js: "window.location='#{molecule_path(@molecule).to_s}'"
  end

  def pubchem_update
    logger.debug "action fired"
    logger.debug "params: #{params}"

    if params[:selection_cid].present?
      id = params[:molecule_id].to_i
      cid = params[:selection_cid].to_i
      logger.debug "cid: #{cid}, id: #{id}"
      @molecule = Molecule.find(params[:molecule_id].to_i)
      @molecule.cid = params[:selection_cid].to_i
      @molecule.full_data(@molecule.cid)
      @molecule.clip_png
      @molecule.add_names
      @molecule.add_cas
      @molecule.save
    end
    redirect_to molecule_path(params[:molecule_id])
  end


  def smilesquery
      regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
      regexresult = Molecule.order(:display_name).where({ iso_smiles: URI.encode(params[:term].upcase) })
      result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
      array = result.map{|n| [n.preferred_abbreviation , n.display_name, n.png_url, n.molecular_weight, n.id, n.iso_smiles]}
      render json: array.sort_by{|word| word[1].length }[0..5]
  end

  def query
      regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
      regexresult = Molecule.select(:preferred_abbreviation, :display_name, :molecular_weight, :png_url, :molecule_type).order(:display_name).where("display_name ILIKE ? OR preferred_abbreviation ILIKE ?", "%#{params[:term]}%", "%#{params[:term]}%")
      result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
      array = result.map{|n| [n.preferred_abbreviation , n.display_name, n.png_url.present? ? n.png_url : "/images/thumb/missing.png", n.molecular_weight, n.molecule_type]}
      render json: array.sort_by{|word| word[1].length }[0..5]
  end


  def query_tags
    #tags = ActsAsTaggableOn::Tag.where("name ILIKE ?", "%#{params[:q]}%")
    tags = ActsAsTaggableOn::Tag.includes(:taggings).where(taggings: {context: "tags"}).where("name ILIKE ?", "%#{params[:q]}%")
    #only tags that are tagged to a molecule (in use) are searched
    render json: tags
  end

  def interactions

  end

  def chemeditor

  end

  def tag_cloud
    authorize Molecule, :editor_or_admin?
    @tags = Molecule.tag_counts_on(:tags)
  end


  def edit_comment
    @comment = params[:molefile]
    flash.now[:warning] = "Nothing found in database Molecules #{params[:molefile]}"
    hash_data = { "Jane Doe" => 10, "Jim Doe" => 6 , "Param" => params[:molefile]}
    molfile = "CWRITER308281317412D\nCreated with ChemWriter - http://chemwriter.com\n  2  1  0  0  0  0  0  0  0  0999 V2000\n   67.4074  -47.2503    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   76.0677  -42.2503    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0\nM  END"
    info_hash = molecule_info_from_molfile(params[:molefile])
    json_data = info_hash.to_json
    render json: json_data
  end


  def hg_sim_data
    base = (0..100).to_a.map{|element| element*0.01}
    c1 = 20./@interaction.binding_constant
    c2 = 2*c1
    ka = @interaction.binding_constant
    x = base.map{|element| element*c2}
    y = x.map{|element| (c1+element+1/ka)/2-Math.sqrt(((c1+element+1/ka)*(c1+element+1/ka))/4-c1*element)}

    sol = x.zip(y).to_h
    xy_data = Hash["jsonarray",sol.map{|x,y| {"x" => x, "y" => y}}].to_json
    #xy_data for chart.js and sol for chartkick

    render json: xy_data
  end

  def external_services
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def pubchem_help
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def pdb_help
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def framework_help
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  def pdb_id_request
    if params[:pdb_id].blank?
      flash.now[:warning] = 'You need to put some PDB ID'
      render partial: 'dbresult'
    else
      unless protein_presence?(params[:pdb_id])
        if valid_pdb_id?(params[:pdb_id])
          @molecule = Molecule.new(preliminary_pdb_data(params[:pdb_id]))
        else
          hash = preliminary_pdb_data(params[:pdb_id])
          case hash[:status]
          when 404
            flash.now[:danger] = "We could not find anything, please verify PDB ID."
          when 500
            flash.now[:danger] = "We are sorry the service is currently unavailable."
          end
        end
        render partial: "molecules/pdb/pdb_preliminary_result"
      else
        @molecule=Molecule.find_by_pdb_id(params[:pdb_id])
        @molecule=Molecule.where("lower(pdb_id) = ?", params[:pdb_id].downcase).first
        flash.now[:success] = "The molecule exists already in the SupraBank"
        render partial: 'molecules/found_result'
      end
    end
  end

  def pubchem_request
    if params[:molecule].blank?
      flash.now[:warning] = 'You need to put some search string'
      render partial: 'dbresult'
    else
      @molecule = Molecule.new
      @molecule.preliminary_data params[:molecule]
      if @molecule.molecule_presence(@molecule.cid)
        @molecule=Molecule.find_by_cid(@molecule.cid)
        flash.now[:success] = "The molecule exists already in the SupraBank."
        render partial: 'molecules/found_result'
      elsif @molecule.cid.present?
        flash.now[:success] = "The molecule is present on PubChem, but not yet at SupraBank, you can retrieve it!"
        render partial: "molecules/preliminary_result"
      else
        flash.now[:warning] = 'Unfortunately, we could not find anything on PubChem. Please first check directly on PubChem for the name and the CID and use here afterwards the "Use CID Instead" option on the right. If the substance is not listed on PubChem, you can create a custom molecule on SupraBank:'
        render partial: "molecules/nothing_found"
      end
    end
  end



  def cid_request
    if params[:request_cid].blank?
      flash.now[:warning] = 'You need to put the PubChem Compound ID (CID)'
      render partial: 'dbresult'
    else
      unless molecule_presence(params[:request_cid])
        @molecule = Molecule.new
        @molecule.preliminary_cid_data params[:request_cid]
        render partial: "molecules/preliminary_result"
      else
        @molecule=Molecule.find_by_cid params[:request_cid]
        flash.now[:success] = "The molecule exists already in the SupraBank"
        render partial: 'molecules/found_result'
      end
    end
  end

  def pdb_full_record
    unless protein_presence?(params[:pdb_id])
      @molecule = Molecule.new(pdb_summary_data(params[:pdb_id]))
      @molecule.display_name = @molecule.pdb_descriptor
      @molecule.preferred_abbreviation = @molecule.display_name
      @molecule.tag_list.add("protein")
      @molecule.clip_protein_png
      @message = "Your molecule was successfully added to the SupraBank"
    else
      @molecule=Molecule.find_by_pdb_id(params[:pdb_id])
      flash.now[:success] = "The molecule exists already in the SupraBank"
    end

    respond_to do |format|
      format.js
    end
  end

  def pubchem_full_record
    @molecule = Molecule.new(cid: params[:cid])
    unless @molecule.molecule_presence(@molecule.cid)
      @molecule.user = current_user
      @molecule.full_data params[:cid]
      @molecule.clip_png
      @molecule.add_names
      @molecule.add_cas
      @molecule.save
      @message = "Your molecule was successfully added to the SupraBank"
    else
      @molecule=Molecule.find_by_cid(params[:cid])
      @message = "The molecule exists already in the SupraBank"
    end

    respond_to do |format|
      format.js
    end
  end


  def listing
    
    @molecules = policy_scope(Molecule).select(:id, :cid, :display_name, :preferred_abbreviation, :molecular_weight, :inchistring, :inchikey, :cano_smiles, :iso_smiles, :interactions_count, :updated_at, :created_at, :png_url)

  end

  def destroy
    authorize @molecule
    @molecule.destroy
    respond_to do |format|
      format.html { redirect_to molecules_path, notice: 'Molecule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def search
    if params[:molecule].blank?
      flash.now[:warning] = 'You need to put some search string'
    else
      @molecule = Molecule.new_from_name(params[:molecule])

      if @molecule.present?
        if @molecule == "exist"
          @molecule = Molecule.dbsearch(params[:molecule]).first
          flash.now[:success] = 'Molecule is already present in the SupraBank'
        else
          @molecule.user = current_user
          @molecule.save
          flash.now[:success] = 'Molecule was added successfully to the SupraBank'
        end
      else
        flash.now[:warning] = 'Nothing found by Name at PubChem. You may try with the CAS number?'
      end
    end
    render partial: 'molecules/result'
  end



  def dbsearch
      if params[:search_param].blank? && params[:tags_param].blank?
        flash.now[:warning] = 'You need to put some content'
        render partial: 'dbresult'
      else

app/helpers/molecules_helper.rb
module MoleculesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/molecules/pdb/_pdb_lookup.html.erb
<div class="col-md-12" >
  <h3 style="margin-top: 30px; margin-bottom: 20 px">PDB powered search <%= link_to (image_tag("logos/rcsb_logo.png", size: "138x38")), "https://www.rcsb.org/", target: :_blank, class:"pull-right" %> </h3>
</div>
<div class="col-md-12">
  <br>
</div>
<div class="" id="cidmolecule-lookup">
  <%= form_tag pdb_id_request_molecules_path, remote: true, method: :get, id: "cidmolecule-lookup-form" do %>
  <div class="form-group row">
    <div class="col-md-8">
      <%= text_field_tag :pdb_id, params[:pdb_id], placeholder: "by PDB ID e.g. 4HHB", autofocus: true, class: "form-control search-box" %>
    </div>
    <div class="col-md-1">
      <div id="cidloader">
        <%= image_tag "preloader/default_trans.gif", size:"32x32"%>
      </div>
    </div>
    <div class="col-md-3">
      <%= button_tag(type: :submit, class: "btn btn-primary search_button", onclick: "showLoader('cid')") do %>
        <i class="fa fa-search"></i> Search by PDB ID
      <% end %>
    </div>

  </div>
  <% end %>
  <div class="container col-md-12" id='cidresults'>
    <%= render 'molecules/result' %>
  </div>

</div>

app/views/molecules/pdb/_pdb_preliminary_result.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9">
      <%= bootstrap_flash %>
    </div>
  </div>
</div>

<% if @molecule  %>
<hr>
    <div class="container col-md-12" id="preliminary_result">
          <div class="container col-md-12">
            <div class="row">
              <h4>We found the following molecule on
                <%= link_to (image_tag("logos/rcsb_logo.png", size: "138x38")), @molecule.pdb_link, target: :_blank %>
              </h4>
            </div>
            <div class="row">
              <div class="col-md-6">
                <table class="table">
                  <tbody>
                    <tr>
                      <td colspan="2" class="no_top_border" ><strong>PDB-ID:</strong></td>
                      <td colspan="2" class="no_top_border"><%= @molecule.pdb_id %> </td>
                    </tr>

                    <tr>
                      <td colspan="2" class="no_top_border" ><strong>Descriptor:</strong></td>
                      <td colspan="2" class="no_top_border"><%= @molecule.pdb_descriptor %> </td>
                    </tr>
                    <tr>
                      <td colspan="2" class="no_top_border" ><strong>Classification:</strong></td>
                      <td colspan="2" class="no_top_border"><%= @molecule.pdb_keywords %> </td>
                    </tr>
                    <tr>
                      <td colspan="2" class="no_top_border" ><strong>Total Structure Weight</strong></td>
                      <td colspan="2" class="no_top_border"><%= @molecule.total_structure_weight %> kDa </td>
                    </tr>
                    <tr>
                      <td colspan="2" class="no_top_border"><strong>Atom Count: </strong></td>
                      <td colspan="2" class="no_top_border"><%= @molecule.atom_count %> </td>
                    </tr>
                    <tr>
                      <td colspan="2" class="no_top_border"><strong>Residue Count: </strong></td>
                      <td colspan="2" class="no_top_border"><%= @molecule.residue_count %> </td>
                    </tr>
                  </tbody>
                </table>

              </div>
              <div class="col-md-6">
                <%= image_tag  "#{@molecule.preferred_abbreviation.gsub(/public/,"")}/protein.png", size: "200x200"%>
              </div>

            </div>
            <div class="row decision-buttons">
              <p><b>Please verify if this is your desired compound.</b></p>
              <%= hidden_field_tag @molecule.id %>
              <button type="button" name="button" class="btn btn-primary " id="reject_button">No (will reject this molecule)</button>
              <%= link_to "Yes (will retrieve full record)", pdb_full_record_molecules_path(:pdb_id => @molecule.pdb_id), remote: true, class:"btn btn-warning", style:"margin-right: 20px;"%>
            </div>
          </div>
        </div>

<% end %>
<script type="text/javascript">
  $(function(){
    $('#reject_button').click(function(){
      $('#preliminary_result').hide()
    });
  });


</script>