config/routes.rb
Rails.application.routes.draw do


  
  root to: 'welcome#welcome'
  get 'about_us', to: 'welcome#about_us'
  get 'terms_of_service', to: 'welcome#terms_of_service'
  get 'privacy', to: 'welcome#privacy'
  get 'legal', to: 'welcome#legal'
  get 'glossary', to: 'glossary#index'
  get 'query_affiliation', to: 'groups#query_affiliation'
  get 'media', to: 'buffers#media'

  resources :charts

  devise_for :users, controllers: {
        registrations: "registrations",
      }, :path_prefix => 'my'

  resources :users, only: [:show] do
    member do
      get :datasets
      get :revisions
      get :interactions
    end
    collection do
      get :query_orcid
      post :orcid_modal
    end
  end

  resources :groups do
    member do
      get :interactions
      get :datasets
    end
    collection do
      get :query
    end
  end

  resources :assignments do
    member do
      get :confirm_group
      get :decline_group
    end
  end

  get 'additives/new', to: redirect('additives')
  get 'solvents/new', to: redirect('solvents')
  resources :additives, :solvents, only: [:index, :show, :edit, :update] do
    member do
      get :interactions
      get :pubchem_update_query
    end
    collection do
      get :pubchem_request
      get :pubchem_full_record
      get :pubchem_update #no controller action yet
      get :cid_request
      get :pubchem_help
      get :search
      get :dbsearch
      get :query
    end
  end

  resources :frameworks do
    member do
      get :preview
    end
    collection do
      get :query
    end
  end
  resources :molecules do
    member do
      get :interactions
      get :pubchem_auto_update
      get :pubchem_update_query
      patch :update_framework_molecule
    end
    collection do
      get :new_framework
      get :new_molecule
      post :create_framework_molecule
      put :pubchem_update
      get :pubchem_request
      get :pubchem_full_record
      get :cid_request
      get :pubchem_help
      get :pdb_help
      get :framework_help
      get :framework_dbsearch
      get :pdb_id_request
      get :pdb_full_record
      get :search
      get :editorsearch
      get :dbsearch
      get :pogresearch
      get :query
      get :smilesquery
      get :query_tags
      get :external_services
      get :tag_cloud
      get :listing
      get :chemeditor
      get :edit_comment
    end
  end

  resources :buffers do
    member do
      get :interactions
    end
    collection do
      get :query
      get :buffer_check
      get :dbsearch
      get :listing
    end
  end
  

  resources :interactions do
    member do
      post :reviewer_comments
      post :duplicate
      put :accident
      get :citation_export
      get :hg_sim_data
      put :self_acceptance
    end
    collection do
      put :publish_accepted
      put :update_reviewers
      get :advsearch
      get :intsearch
      get :dbsearch
      get :advanced_search
      get :query_technique
      get :query_assay_type
      get :query_itc_instruments
    end
  end

  resources :creators, :contributors, only: [] do
    collection do
      post :orcid_modal
      get :query
    end
  end

  resources :datasets do
    collection do
      post :preview_modal
      put :add_interactions
      put :update_state
      put :update_dataset_interactions_dois
      put :remove_interactions
      get :list_all_possible_interactions
      get :citation_query
      get :query_user_datasets_editable
      get :query_datasets
      get :query_cooperators
      get :advsearch
      get :query_subjects
    end

    member do
      put :self_revision_temp
      get :preview
      get :dataset_csv_export
      get :interaction_addition
      get :citation_export
    end
  end

  resources :related_identifiers, only: [] do
    member do
      get :citation_export
    end
  end

  resources :dataset_related_identifiers, only: [] do
    collection do
      get :primary_reference_doi_query
    end
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  include Orcid
  enum user_role: {user: 0, group_admin: 1, admin: 2, editor: 3}

  after_initialize :set_default_role, :if => :new_record?
  after_initialize :set_default_group_role, :if => :new_record?


scope :users, -> { where(user_role: 0)}
scope :group_admins, -> { where(user_role: 1) }
scope :admins, -> { where(user_role: 2) }
scope :editors, -> { where(user_role: 3) }




  scope :reviewers, -> { where(email: ::ReviewerSet.to_a) }


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
 has_attached_file :avatar, styles: { medium: "250x250>", thumb: "60x60>" }, default_url: "/images/:style/blank-user-profile.png"
 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
 validates :email, 'valid_email_2/email': { mx: true, disposable_with_whitelist: true, disallow_subaddressing: true, blacklist: true, message: "is not a valid email"}

 has_many :buffers
 has_many :interactions
 has_many :assignments, dependent: :delete_all
 has_many :groups, through: :assignments
 has_many :dataset_users
 has_many :datasets, :through => :dataset_users
 accepts_nested_attributes_for :assignments, :allow_destroy => true
 accepts_nested_attributes_for :groups, :allow_destroy => true
 #validate :one_group_leader
 before_save :refine_url
 validate :givenName_validity, :familyName_validity
 before_save :update_assignment

 before_save :sync_cooperators

 def update_assignment
   assignment = Assignment.find_by_user_id(id)
 end

 def givenName_validity
   if givenName.present?
     if URI.extract(givenName).present?
       errors.add(:givenName, "Please provide a valid given name, URLs are not allowed!")
     end
   end
 end

 def familyName_validity
   if familyName.present?
     if URI.extract(familyName).present?
       errors.add(:familyName, "Please provide a valid family name, URLs are not allowed!")
     end
   end
 end

 def set_default_role
   self.user_role ||= :user
 end

 def set_default_group_role
   self.role ||= "independent"
 end

 def self.find_creator(user)
   if user.nameIdentifier.present?
     begin
       search = Creator.where(nameIdentifier: user.nameIdentifier)
     rescue ActiveRecord::RecordNotFound
       search = Creator.where('"givenName" = ? AND "familyName" = ?',"#{user.givenName}","#{user.familyName}")
     end
   else
     search = Creator.where('"givenName" = ? AND "familyName" = ?',"#{user.givenName}","#{user.familyName}")
   end
   return search
 end

 def update_creator
   search = User.find_creator(self)
   if search.present?
     search.first.update({givenName: self.givenName, familyName:self.familyName, nameIdentifier:self.nameIdentifier, affiliation:self.affiliation, affiliationIdentifier:self.affiliationIdentifier})
   else
     Creator.create({givenName: self.givenName, familyName:self.familyName, nameIdentifier:self.nameIdentifier, affiliation:self.affiliation, affiliationIdentifier:self.affiliationIdentifier})
   end
 end

 def self.find_contributor(user)
   if user.nameIdentifier.present?
     begin
       search = Contributor.where(nameIdentifier: user.nameIdentifier)
     rescue ActiveRecord::RecordNotFound
       search = Contributor.where('"givenName" = ? AND "familyName" = ?',"#{user.givenName}","#{user.familyName}")
     end
   else
     search = Contributor.where('"givenName" = ? AND "familyName" = ?',"#{user.givenName}","#{user.familyName}")
   end
   logger.debug "Here comes the log from searching a user like contributor:#{search}"
   return search
 end

 def update_contributor
   search = User.find_contributor(self)
   if search.present?
     search.first.update({givenName: self.givenName, familyName:self.familyName, nameIdentifier:self.nameIdentifier, affiliation:self.affiliation, affiliationIdentifier:self.affiliationIdentifier})
   else
     Contributor.create({givenName: self.givenName, familyName:self.familyName, nameIdentifier:self.nameIdentifier, affiliation:self.affiliation, affiliationIdentifier:self.affiliationIdentifier})
   end
 end


  def sync_cooperators
    self.update_creator
    self.update_contributor
  end


 def listed_reviewer?
    if User.reviewers.include? self
      return true
    else
      false
    end
 end

  def full_name
    return "#{givenName} #{familyName}".strip if (givenName||familyName)
    'Anonymous'
  end

  def setup_assignments
    self.assignments.build
  end

def desired_group_name
  unless self.assignments.first.present?
    self.assignments << Assignment.new
  end
    self.assignments.first.desired_group.try(:name)
end

 def group_name
  unless self.assignments.first.present?
    self.assignments << Assignment.new
  end
   self.assignments.first.group.try(:name)
 end

 def group_name=(name)
   unless self.assignments.first.present?
     self.assignments << Assignment.new
   end
   if name.present?
     group = Group.find_by(name: name)
     if group.present?
       self.assignments.first.group = group
     else
       unless self.assignments.first.group.present?

         self.assignments.first.group = Group.new
       end
       self.assignments.first.group.name = name
     end
   end
 end

 def desired_group_name=(name)

   if self.assignments.first.present?
     assignment =  self.assignments.first
   else
     assignment =  Assignment.new
   end

   if Group.find_by(name: name).present?
     desiredGroup = Group.find_by(name: name)
   else
     desiredGroup = Group.create(name: name)
   end

   assignment.update(desired_group: desiredGroup)

 end

def role
  self.assignments.first.try(:role)
end

def desired_role
  self.assignments.first.try(:desired_role)
end

def role=(name)
  unless self.assignments.first.present?
    self.assignments << Assignment.new
  end
  self.assignments.first.role = name if name.present?
end

def desired_role=(name)
  if self.assignments.first.present?
    assignment =  self.assignments.first
  else
    assignment =  Assignment.new
  end
  assignment.update(desired_role: name)
end


def refine_url
  if self.url.present?
    result = self.url =~ URI::regexp
    unless result.present?
      self.url = "http://"+self.url
    end
  end
end

#custom validations

# def one_group_leader
#     if self.assignments.first.group.users.where(role: "Group Leader").size >= 1
#       errors.add(:role, "There can only be one group leader per group")
#     end
# end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :interactions, :revisions, :datasets]
  before_action :set_meta_data
  before_action :authenticate_user!, except: [:query_orcid, :orcid_modal]


  include Orcid

  def index

  end

  def show
    @interactions = @user.interactions.active
    @groupinteractions = @user.groups.present? ?  @user.groups.first.group_interactions : nil
    @groupdatasets = @user.groups.present? ?  @user.groups.first.group_datasets : nil
    #UserMailer.welcome_email(@user).deliver!
  end

  def interactions
    authorize @user, :show?
    @qpublished = @user.interactions.published.ransack(params[:q])
    @published = @qpublished.result
    @interactions_published = Kaminari.paginate_array(@published).page(params[:page]).per(10)
  end

  def datasets
    authorize @user, :show?
    @datasets = @user.datasets
  end

  def orcid_modal
    array = query_name_array_from_name(params[:familyName],params[:givenName])
    #logger.debug "#{array}"
    #array = query_name_array_from_name("Sinn","Stephan")

    @orcid_results = array
    #logger.debug "#{@orcid_results}"
    respond_to do |format|
      format.html
      format.js
    end
  end


  def query_orcid

    array = query_name_array_from_name(params[:familyName],params[:givenName])
    @orcid_results = array
    logger.debug "#{array}"
    logger.debug "#{@orcid_results}"
    render json: array
  end

  def revisions
    authorize @user, :revisions?
    @interactions = InteractionPolicy::Moderator.new(@user, Interaction).resolve

    @qsubmitted = @interactions.submitted.ransack(params[:q])
    @submitted = @qsubmitted.result
    @interactions_submitted = Kaminari.paginate_array(@submitted).page(params[:page]).per(10)
    #
    # @qpending = @interactions.pending.ransack(params[:q])
    # @pending = @qpending.result
    @interactions_pending = @interactions.pending
    #
    # @qaccepted = @interactions.accepted.ransack(params[:q])
    # @accepted = @qaccepted.result
    @interactions_accepted = @interactions.accepted

  end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      def set_meta_data
        if @user.present?
          @title = "SupraBank - Users - #{@user.full_name}"
          #generic
          @meta_title = @title
          @meta_description = "User  #{@user.full_name} at SupraBank"
          @meta_image = @user.avatar.present? ? @user.avatar.url : "logo-production.png"
          #open graph facebook
          @meta_og_url = polymorphic_url(@user, host:"https://suprabank.org", :protocol => 'https' )
          # twitter card markup
        else
          @title = "SupraBank - Users"
          @meta_title = @title
          @meta_description = "Find the contributing users at SupraBank"
          @meta_image = "logo-production.png"
          @meta_og_url = "https://suprabank.org/users"
        end
      end


      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.fetch(:user, {})
        params.require(:user).permit(:avatar, :givenName, :familyName, :png, :affiliation, :affiliationIdentifier)
      end
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/views/users/interactions/_info_td.html.erb
<table class="table table-info">
  <thead>
    <tr>
      <th class="col-md-2">
        <% if interaction.revision == "accepted" && interaction.user == current_user %>
          <span class="has-tooltip" id="has-tooltip" data-toggle="ajax-tooltip" title="Select to publish">
            <%= check_box_tag "interaction_ids[]", interaction.id %>
          </span>
        <% end %>
      </th>
      <th class="col-md-2">
        <span class="has-tooltip" id="has-tooltip" data-toggle="ajax-tooltip" title="<%= "Show  #{interaction.assay_type} between #{interaction.molecule.display_name} and #{interaction.host.display_name}" %>">
          <%= link_to "", {controller: "interactions", action: 'show', id: interaction.id}, class:'far fa-eye', target:"_blank"%>
        </span>
      </th>
      <th class="col-md-2">
        <span class="has-tooltip" data-toggle="ajax-tooltip" title="<%= "Clone this interaciton" %>">
          <%= link_to "", {controller: "interactions", action: 'duplicate', id: interaction.id}, class:'fas fa-clone', :method=>:post%>
        </span>
      </th>
      <th class="col-md-2">
        <span class="has-tooltip" data-toggle="ajax-tooltip" title="Citation">
          <span class="has-js-popover citation_popover" data-toggle="top-popover" data-container="body" title= "<span class='text-info'><strong>Citation</strong></span>
        <button type='button' id='close' class='close' onclick='$(&quot;.citation_popover&quot;).popover(&quot;hide&quot;);' > &times;</button>"
          data-content='
          <div class="">
            <%= interaction.citation %>
          </div>
          <div class="">
            <%= link_to interaction.doi, "https://doi.org/#{interaction.doi}", target: :_blank, class:"external-link", "rel" => "noopener noreferrer"%>
          </div>
          ' >
              <i class="fas fa-quote-right"></i>
          </span>

        </span>
      </th>
      <th class="col-md-2">
          <% if interaction.solvents.present? %>
          <span class="has-tooltip " data-toggle="ajax-tooltip" title="<%= interaction.solvents.first.preferred_abbreviation %>">
            <% if interaction.solvents.first.preferred_abbreviation == "water" %>
              <i class="fas fa-tint aqueous"></i>
            <% else %>
              <i class="fas fa-tint organic"></i>
            <% end %>
          </span>
          <% else %>
          <span class="has-tooltip " data-toggle="ajax-tooltip" title="No Solvent">
            <i class="fas fa-tint-slash"></i>
          </span>
          <% end %>
      </th>
      <th class="col-md-2">
        <span class="has-tooltip " data-toggle="ajax-tooltip" title="<%= AssayType.search_by_names(interaction.assay_type).first.names[0] if interaction.assay_type.present? %>">
          <% if interaction.assay_type == "Direct Binding Assay" %>
            <span class="icon-dba <%= AssayType.search_by_names(interaction.assay_type).first.names[1] if interaction.assay_type.present? %>"></span>
          <% elsif interaction.assay_type == 'Competitive Binding Assay' %>
            <span class="icon-cba <%= AssayType.search_by_names(interaction.assay_type).first.names[1] if interaction.assay_type.present? %>"></span>
          <% elsif interaction.assay_type == "Associative Binding Assay" %>
            <span class="icon-aba <%= AssayType.search_by_names(interaction.assay_type).first.names[1] if interaction.assay_type.present? %>"></span>
          <% else %>
          <% end %>
        </span>
      </th>
      <th class="col-md-2">
        <span class="has-tooltip " data-toggle="ajax-tooltip" title="<%= Technique.search_by_names(interaction.technique).first.names[0] if interaction.technique.present? %>">
            <span class="icon-<%= Technique.search_by_names(interaction.technique).first.names[1].downcase if interaction.technique.present? %> <%= Technique.search_by_names(interaction.technique).first.names[1] if interaction.technique.present? %>" ></span>
        </span>
      </th>

    </tr>
  </thead>

</table>

app/views/users/interactions/_table.html.erb
<div class="table-responsive">
 <table class="table col-md-12" id="int-index-<%= table_id %>" data-turbolinks='false'>
  <thead>
    <tr>
      <th class="col-md-2 no-sort">Actions / Info</th>
      <th class="no-sort" style="text-align: right;">
         <button class="btn btn-sm btn-primary has-tooltip " id="tableMolName-<%= table_id %>" type="button" data-toggle="tooltip" title="Show structures" onclick="viewMolStructure('<%= table_id %>')">
           <%= image_tag "struc.svg", size:"17x17" %>
         </button></th>
      <th class="col-md-2"><span >Molecule</span> </th>
        <th class="no-sort" style="text-align: right;">
           <button class="btn btn-sm btn-primary has-tooltip " id="tableMolStruc-<%= table_id %>" type="button" data-toggle="tooltip" title="Show names" onclick="viewMolNames('<%= table_id %>')">
                <i class="fa fa-list" aria-hidden="true"></i>
           </button></th>
      <th class="col-md-2" ><span >Molecule</span></th>
      <th class="no-sort" style="text-align: right;">
         <button class="btn btn-sm btn-primary has-tooltip " id="tablePartName-<%= table_id %>" type="button" data-toggle="tooltip" title="Show structures" onclick="viewPartStructure('<%= table_id %>')">
            <%= image_tag "struc.svg", size:"17x17" %>
         </button></th>
      <th class="col-md-2"><span >Partner</span></th>
      <th class="no-sort" style="text-align: right;">
           <button class="btn btn-sm btn-primary has-tooltip " id="tablePartStruc-<%= table_id %>"type="button" data-toggle="tooltip" title="Show names" onclick="viewPartNames('<%= table_id %>')">
                <i class="fa fa-list" aria-hidden="true"></i>
           </button></th>
      <th class="col-md-2" ><span >Partner</span></th>
      <th class="no-sort"></th>
      <th class="col-md-1"><span class="has-tooltip" data-toggle="tooltip" title="decadic logarithm of the binding constant">log <em>K</em><sub>a</sub> </span></th>
      <th class="col-md-1">Medium</th>
      <th class="col-md-1"><span class="has-tooltip" data-toggle="tooltip" title="Measurement Temperature">T / °C</span></th>
  <!--    <th class="col-md-1"><span class="has-tooltip" data-toggle="tooltip" title="Total Concentration">C / mM</span></th> -->
      <th class="col-md-1  no-sort">Supplement</th>

    </tr>
  </thead>
  <tbody>
    <% interactions.each do |interaction| %>

      <% if policy(interaction).displayable? %>
      <tr>
        <td class="col-md-2 tight-column">
          <%= render "users/interactions/info_td", interaction:interaction %>

        </td>

        <td class="" >
        </td>
          <td class="col-md-2">
            <% if interaction.molecule.present? %>
              <span class="has-tooltip" data-toggle="ajax-tooltip" title="<%= "#{interaction.molecule.display_name}" %>">
                <span class="has-js-popover structure_popover_molecule" data-toggle="ajax-popover" data-container="body" title= "<span class='text-info'><strong>Structure</strong></span>
                      <button type='button' id='close' class='close' onclick='$(&quot;.structure_popover_molecule&quot;).popover(&quot;hide&quot;);' > &times;</button>"
                      style=""
                data-content='
                <div class="center" structure-image-panel">
                  <input type="checkbox" id="zoomCheck" class="zoomCheck">
                  <label for="zoomCheck">
                    <%= image_tag interaction.molecule.png_url, class:"popover_molecule_image"%>
                  </label>
                    <p><%= link_to "Show all Information", molecule_path(interaction.molecule), target:"_blank" %></p>
                </div>
                ' >
                <%= interaction.molecule.preferred_abbreviation.present? ? interaction.molecule.preferred_abbreviation.truncate(15) : truncate(interaction.molecule.display_name, length: 15) %>
              </span>
            </span>
            <% end %>
          </td>

          <td class="" >
          </td>

          <td class="col-md-2" style="height: 160px">
            <% if interaction.molecule.present? %>
            <span style="display: none"> <%= interaction.molecule.preferred_abbreviation.present? ? interaction.molecule.preferred_abbreviation.truncate(15) : truncate(interaction.molecule.display_name, length: 15)%> </span>
            <span class="has-tooltip" data-toggle="ajax-tooltip" title="<%= truncate(interaction.molecule.display_name, length: 30) %>">
              <span class="has-js-popover name_popover_molecule"  data-container="body" data-toggle="ajax-popover" title= "<span class='text-info'><strong>Name</strong></span>
                    <button type='button' id='close' class='close' onclick='$(&quot;.name_popover_molecule&quot;).popover(&quot;hide&quot;);' > &times;</button>"
                    style=""
              data-content='
              <div class="center structure-image-panel">
                <input type="checkbox" id="zoomCheck" class="zoomCheck">
                <label for="zoomCheck">
                <%= "#{interaction.molecule.display_name}" %>
                </label>
                      <p><%= link_to "Show all information", molecule_path(interaction.molecule), target:"_blank" %></p>
              </div>
              ' >
                  <%= image_tag interaction.molecule.png_url, class: 'interaction-structure-image'%>
              </span>
            </span>
            <% end %>
          </td>

          <td class="" >
          </td>

          <td class="col-md-2">
            <% if interaction.host.present? %>
              <span class="has-tooltip" data-toggle="ajax-tooltip" title="<%= interaction.host.present? ? "#{interaction.host.display_name}" : "no host" %>">
                <span class="has-js-popover structure_popover_host"  data-container="body" data-toggle="ajax-popover" title= "<span class='text-info'><strong>Structure</strong></span>
                      <button type='button' id='close' class='close' onclick='$(&quot;.structure_popover_host&quot;).popover(&quot;hide&quot;);' > &times;</button>"
                      style=""
                data-content='
                <div class="center structure-image-panel">
                  <input type="checkbox" id="zoomCheck" class="zoomCheck">
                  <label for="zoomCheck">
                    <%= image_tag interaction.host.png_url, class:"popover_molecule_image"%>
                  </label>
                  <p><%= link_to "Show all Information", molecule_path(interaction.host), target:"_blank" %></p>
               </div>
                ' >
                  <%= interaction.host.preferred_abbreviation.present? ? interaction.host.preferred_abbreviation.truncate(15) :  truncate(interaction.host.display_name, length: 15) %>
                </span>
              </span>
            <% end %>
          </td>

          <td class="" >
          </td>

          <td class="col-md-2" style="height: 160px">
            <% if interaction.host.present? %>
            <span style="display: none"> <%= interaction.host.preferred_abbreviation.present? ? interaction.host.preferred_abbreviation.truncate(15) : truncate(interaction.host.display_name, length: 15)%> </span>
            <span class="has-tooltip" data-toggle="ajax-tooltip" title="<%= truncate(interaction.host.display_name, length: 30) %>">
              <span class="has-js-popover structure_popover_host"  data-container="body" data-toggle="ajax-popover" title= "<span class='text-info'><strong> Name </strong></span>
                    <button type='button' id='close' class='close' onclick='$(&quot;.structure_popover_host&quot;).popover(&quot;hide&quot;);' > &times;</button>"
                    style=""
              data-content='
                    <div class="center structure-image-panel">
                    <input type="checkbox" id="zoomCheck" class="zoomCheck">
                    <label for="zoomCheck">
                    <%= "#{interaction.host.display_name}" %>
                    </label>
                          <p><%= link_to "Show all information", molecule_path(interaction.host), target:"_blank" %></p>
                  </div>
                  ' >
                      <%= image_tag interaction.host.png_url, class: 'interaction-structure-image'%>
              </span>
            </span>
            <% end %>
          </td>

          <td class="center">
              <% if interaction.binding_constant.present?  %>
              <span>
                  <% case interaction.binding_range
                          when "greater" %>
                            >
                          <% when "less" %>
                            <
                  <%  end %>
              </span>
            <% end %>
          </td>

          <td class="col-md-1 center">
              <% if interaction.logKa.present?  %>
                <span>
                <%=  interaction.logKa.round(2) %>
                </span>
              <% end %>
          </td>


          <td class="col-md-1">
            <% if interaction.solvent_system.present?  %>
              <% if interaction.solvent_system == "Single Solvent"  %>

                <% if interaction.solvents.first.present?  %>
                <span class="has-tooltip" data-toggle="ajax-tooltip" title="<%= "#{interaction.solvents.first.display_name}" %>">
                <%= interaction.solvents.first.display_name %>
                </span>
                <% end %>

              <% elsif interaction.solvent_system == "Complex Mixture" %>
                <span class="has-tooltip" data-toggle="tooltip" title="<%= "#{interaction.solvent_system}" %>">
                <p>Complex</p>
                </span>

              <% elsif interaction.solvent_system == "Buffer System" %>
                <% if interaction.buffer.present? %>
                  <span class="has-tooltip" data-toggle="tooltip" title="<%= interaction.buffer.name if interaction.buffer.name.present? %>">
                    <%= interaction.buffer.abbreviation.present? ? interaction.buffer.abbreviation.truncate(8) : interaction.buffer.name.truncate(8) %>
                  </span>
                <% end %>
              <% end %>
            <% end %>
          </td>

          <td class="col-md-1">
            <span class="has-tooltip" data-toggle="tooltip" title="<%= "T =  #{273.15 + interaction.temperature} K" %>">
            <%= interaction.temperature %>
          </span>
          </td>

  <!--        <td class="col-md-1" >

            <%= interaction.ionic_strength %>

          </td>   -->

          <td class="col-md-1">


                <% if interaction.assay_type == 'Competitive Binding Assay' %>
                  <% if interaction.indicator.present? %>
                  <span class="has-tooltip " data-toggle="left-tooltip" title="<%= interaction.indicator.present? ? "#{interaction.indicator.display_name}" : "no indicator" %>">
                    <span class="has-js-popover structure_popover_indicator"  data-container="body" data-toggle="popover" title="Indicator: <%= interaction.indicator.display_name if interaction.indicator.present? %> <button type='button' id='close' class='close' onclick='$(&quot;.structure_popover_indicator&quot;).popover(&quot;hide&quot;);' > &times;</button>"
                    data-content='
                      <div class="center">
                        <% if interaction.indicator.present? %>
                          <%= image_tag interaction.indicator.png_url, class:"popover_molecule_image"%>
                          <p><%= link_to "Show all Information", molecule_path(interaction.indicator) %></p>
                        <% end %>
                      </div>
                    ' >
                      <%= interaction.indicator.preferred_abbreviation.present? ? interaction.indicator.preferred_abbreviation.truncate(15) : truncate(interaction.indicator.display_name, length: 15) %>
                    </span>
                  </span>
                  <% end %>
                <% elsif interaction.assay_type == "Associative Binding Assay" %>
                  <% if interaction.conjugate.present? %>
                  <span class="has-tooltip " data-toggle="left-tooltip" title="<%= interaction.conjugate.present? ? "#{interaction.conjugate.display_name}" : "no host" %>">
                    <span class="has-js-popover structure_popover_conjugate"  data-container="body" data-toggle="popover" title="Cofactor: <%= interaction.conjugate.display_name if interaction.conjugate.present? %> <button type='button' id='close' class='close' onclick='$(&quot;.structure_popover_conjugate&quot;).popover(&quot;hide&quot;);' > &times;</button>"
                    data-content='
                      <div class="center">
                        <% if interaction.conjugate.present? %>
                          <%= image_tag interaction.conjugate.png_url, class:"popover_molecule_image"%>
                          <p><%= link_to "Show all Information", molecule_path(interaction.conjugate) %></p>
                        <% end %>
                      </div>
                    ' >
                      <%= interaction.conjugate.preferred_abbreviation.present? ? interaction.conjugate.preferred_abbreviation.truncate(15) : truncate(interaction.conjugate.display_name, length: 15) %>
                    </span>
                  </span>
                  <% end %>
                <% else %>
                <% end %>


          </td>


        </tr>
      <% end %>
      <% end %>

  </tbody>
</table>
</div>

<script type="text/javascript">
  window.alert = (function() {
    var nativeAlert = window.alert;
    return function(message) {
        window.alert = nativeAlert;
        message.indexOf("DataTables warning") === 0 ?
            console.warn(message) :
            nativeAlert(message);
    }
  })();
</script>