config/routes.rb
Rails.application.routes.draw do


  
  root to: 'welcome#welcome'
  get 'about_us', to: 'welcome#about_us'
  get 'terms_of_service', to: 'welcome#terms_of_service'
  get 'privacy', to: 'welcome#privacy'
  get 'legal', to: 'welcome#legal'
  get 'glossary', to: 'glossary#index'
  get 'query_affiliation', to: 'groups#query_affiliation'
  get 'media', to: 'buffers#media'

  resources :charts

  devise_for :users, controllers: {
        registrations: "registrations",
      }, :path_prefix => 'my'

  resources :users, only: [:show] do
    member do
      get :datasets
      get :revisions
      get :interactions
    end
    collection do
      get :query_orcid
      post :orcid_modal
    end
  end

  resources :groups do
    member do
      get :interactions
      get :datasets
    end
    collection do
      get :query
    end
  end

  resources :assignments do
    member do
      get :confirm_group
      get :decline_group
    end
  end

  get 'additives/new', to: redirect('additives')
  get 'solvents/new', to: redirect('solvents')
  resources :additives, :solvents, only: [:index, :show, :edit, :update] do
    member do
      get :interactions
      get :pubchem_update_query
    end
    collection do
      get :pubchem_request
      get :pubchem_full_record
      get :pubchem_update #no controller action yet
      get :cid_request
      get :pubchem_help
      get :search
      get :dbsearch
      get :query
    end
  end

  resources :frameworks do
    member do
      get :preview
    end
    collection do
      get :query
    end
  end
  resources :molecules do
    member do
      get :interactions
      get :pubchem_auto_update
      get :pubchem_update_query
      patch :update_framework_molecule
    end
    collection do
      get :new_framework
      get :new_molecule
      post :create_framework_molecule
      put :pubchem_update
      get :pubchem_request
      get :pubchem_full_record
      get :cid_request
      get :pubchem_help
      get :pdb_help
      get :framework_help
      get :framework_dbsearch
      get :pdb_id_request
      get :pdb_full_record
      get :search
      get :editorsearch
      get :dbsearch
      get :pogresearch
      get :query
      get :smilesquery
      get :query_tags
      get :external_services
      get :tag_cloud
      get :listing
      get :chemeditor
      get :edit_comment
    end
  end

  resources :buffers do
    member do
      get :interactions
    end
    collection do
      get :query
      get :buffer_check
      get :dbsearch
      get :listing
    end
  end
  

  resources :interactions do
    member do
      post :reviewer_comments
      post :duplicate
      put :accident
      get :citation_export
      get :hg_sim_data
      put :self_acceptance
    end
    collection do
      put :publish_accepted
      put :update_reviewers
      get :advsearch
      get :intsearch
      get :dbsearch
      get :advanced_search
      get :query_technique
      get :query_assay_type
      get :query_itc_instruments
    end
  end

  resources :creators, :contributors, only: [] do
    collection do
      post :orcid_modal
      get :query
    end
  end

  resources :datasets do
    collection do
      post :preview_modal
      put :add_interactions
      put :update_state
      put :update_dataset_interactions_dois
      put :remove_interactions
      get :list_all_possible_interactions
      get :citation_query
      get :query_user_datasets_editable
      get :query_datasets
      get :query_cooperators
      get :advsearch
      get :query_subjects
    end

    member do
      put :self_revision_temp
      get :preview
      get :dataset_csv_export
      get :interaction_addition
      get :citation_export
    end
  end

  resources :related_identifiers, only: [] do
    member do
      get :citation_export
    end
  end

  resources :dataset_related_identifiers, only: [] do
    collection do
      get :primary_reference_doi_query
    end
  end



end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  include ActionView::Helpers::NumberHelper # <-
  include Technology
  include Colors
  before_action :set_interaction, only: [:show, :edit, :update, :destroy, :hg_sim_data, :solvent_check, :citation_export, :reviewer_comments, :accident, :self_acceptance]
  before_action :set_meta_data
  before_action :authenticate_user!, except: [:show, :citation_export, :index, :intsearch, :advanced_search, :advsearch, :dbsearch, :hg_sim_data, :query_technique, :query_assay_type]

  def dataset_update
      Interaction.update_all({},{id: params[:interaction_ids]})
  end


    # GET /interactions
    # GET /interactions.json

  def self_acceptance
    @dataset = @interaction.dataset
    authorize @dataset, :self_revision_interaction?
    @interaction.update(revision: 'submitted')
    flash[:success] = "Your interaction was revised by yourself and is currently 'submitted'. When all interactions are revised you may accept them from within the dataset."
    redirect_to  dataset_path(@dataset)
  end
  


    def advanced_search
      @interactions = nil
      @techniques=Technique.all
      @q = Interaction.published.ransack(query_params)
      @selection = @q.result
      if query_params.present?
        @interactions = Kaminari.paginate_array(@selection).page(params[:page]).per(10)
      end
      respond_to do |format|
        format.html
        format.js
      end
    end

    def query_itc_instruments
        regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
        regexresult = ItcInstrument.order(:name).where("name ILIKE ? OR alternative_name ILIKE ? OR brand ILIKE ?", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
        result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
        array = result.map{|n| [n.name , n.alternative_name, n.brand, n.cell_volume, n.syringe_volume]}
        render json: array
        #render json: result.to_json
    end


    def query_technique
          regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
          t1=Technique.where("names && ?", "{#{params[:term].upcase}}")
          t2=Technique.order(:names).where("names[1] ILIKE ?", "%#{params[:term]}%")
          regexresult = (t1+t2).uniq
          #regexresult = Technique.order(:names).where("names ILIKE ? ", "%#{params[:term]}%")
          result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
          array = result.map{|n| [n.names[0], n.names[1], n.names[2]]}
          render json: array.sort_by{|word| word[1].length }
    end

    def query_assay_type
          regexp = /#{params[:term]}/i; # case-insensitive regexp based on your string
          a1=AssayType.where("names && ?", "{#{params[:term].upcase}}")
          a2=AssayType.order(:names).where("names[1] ILIKE ?", "%#{params[:term]}%")
          regexresult = (a1+a2).uniq
          result= regexresult.sort{|x, y| (x =~ regexp) <=> (y =~ regexp) }
          array = result.map{|n| [n.names[0], n.names[1]]}
          render json: array.sort_by{|word| word[1].length }
    end



    def dbsearch
      if params[:search_param].blank?
        flash.now[:warning] = 'You need to put some content'
        render partial: 'dbresult'
      else
        @interactions = Interaction.includes(:molecule).order(updated_at: :desc).dbsearch(params[:search_param])
        if @interactions.present?
          #@interactions=@interactions[0..199]
          render partial: 'dbresult'
        else
          input = params[:search_param]
          response = input[0..(input.length/2)]
          flash.now[:warning] = "No Interaction was found, please use wildcards like <strong>#{response}%</strong>".html_safe if @interactions.blank?

          render partial: 'dbresult'
        end
      end
    end

    # def advsearch
    #   if params[:molecule_param].blank? & params[:mol_tags_param].blank? & params[:host_param].blank? & params[:host_tags_param].blank? & params[:binding_param].blank? & params[:binding_to_param].blank? & params[:technique_param].blank? & params[:assay_type_param].blank? & params[:supplement_param].blank? & params[:doi_param].blank? & params[:author_param].blank? & params[:year_param].blank? & params[:solvent_param].blank? & params[:buffer_param].blank? & params[:pH_param].blank? & params[:pH_to_param].blank? & params[:temperature_param].blank? & params[:temperature_to_param].blank?
    #     flash.now[:warning] = 'You need to put some content'
    #     render partial: 'advresult'
    #   else
    #     @interactions = Interaction.advsearch(params[:molecule_param],params[:mol_tags_param],params[:host_param],params[:host_tags_param],params[:binding_param],params[:binding_to_param],params[:technique_param],params[:assay_type_param],params[:supplement_param], params[:doi_param], params[:author_param], params[:year_param], params[:solvent_param], params[:buffer_param], params[:pH_param], params[:pH_to_param], params[:temperature_param], params[:temperature_to_param], params[:molecule_exclusive_param], params[:host_exclusive_param], params[:host_or_param])
    #     if @interactions.present?
    #       #@interactions=@interactions[0..199]
    #       render partial: 'advresult'
    #     else
    #       #input = params[:search_param]
    #       #response = input[0..(input.length/2)]
    #       flash.now[:warning] = "No Interaction was found." if @interactions.blank?
    #       render partial: 'advresult'
    #     end
    #   end
    # end

    

    def pogresearch
        if params[:search_param].blank?
          flash.now[:warning] = 'You need to put some content'
          render partial: 'pgresult'
        else
          @interactions = Interaction.search_by_doi(params[:search_param])
          if @interactions.present?
            render partial: 'pgresult'
          else
            flash.now[:warning] = 'Nothing found in the database Molecules' if @molecules.blank?
            render partial: 'pgresult'
          end
        end
    end

    def solvent_check
      if true
        render "hello"
      end
    end

    def hg_sim_data
      base = (0..100).to_a.map{|element| element*0.01}
      c1 = 20./@interaction.binding_constant
      c2 = 2*c1
      ka = @interaction.binding_constant
      x = base.map{|element| element*c2}
      y = x.map{|element| (c1+element+1/ka)/2-Math.sqrt(((c1+element+1/ka)*(c1+element+1/ka))/4-c1*element)}

      sol = x.zip(y).to_h
      xy_data = Hash["jsonarray",sol.map{|x,y| {"x" => x, "y" => y}}].to_json
      #xy_data for chart.js and sol for chartkick

      render json: xy_data
    end


    def duplicate
      @interaction = Interaction.duplicate(params[:id], current_user, params[:dataset_id])
     respond_to do |format|
        if @interaction.save
          format.html { redirect_to edit_interaction_path(@interaction), notice: 'Item was successfully created. Please make sure to edit it now. Avoid simple duplicates.' }
        else
          format.html {  redirect_to Interaction.find(params[:id]), notice: 'ERROR: Item can\'t be cloned.'}
        end
      end
    end


    def index
      @q = Interaction.includes(:molecule, :host, :in_technique, :buffer, :user, :indicator, :conjugate, :datasets, :interaction_solvents, :solvents, :interaction_additives, :additives, :interaction_related_identifiers, :related_identifiers).published.order(updated_at: :desc).limit(200).ransack(params[:q])
      @selection = @q.result
      @interactions = Kaminari.paginate_array(@selection).page(params[:page]).per(10)
      respond_to do |format|
        format.html
        format.js
      end
    end

    def intsearch
      @interactions = Interaction.order(updated_at: :desc)
    end

    # GET /interactions/1
    # GET /interactions/1.json
    def show
      authorize @interaction, :revision_embargoed?
      @dataset = @interaction.dataset
      if @interaction.published? && @dataset.present?
        unless session[@dataset.id.to_s + "interaction_show_count"]
          @interaction.increment!(:show_count) if @interaction.published?
          @interaction.dataset&.increment!(:view_count) if @interaction.dataset&.state == "findable"
          session[@dataset.id.to_s + "interaction_show_count"] = true
        end
      end
    end

    # GET /interactions/new
    def new
      @interaction = Interaction.new
      @dataset = Dataset.find(params[:dataset_id]) if params[:dataset_id].present?
      #@interaction.embargo = false
    end

    # GET /interactions/1/edit
    def edit
      authorize @interaction, :revision_published?
      @interaction.solvent_additive_checkup
      @dataset = @interaction.dataset
    end

    def reviewer_comments
      authorize @interaction, :revision_submitted?
      respond_to do |format|
        if @interaction.update(interaction_params)
          @interaction.save
          format.html { redirect_to @interaction, notice: 'Thank you for your review. The creator will be informed soon about the current status.' }
        else
          format.html { render @interaction }
        end
      end
    end

    def publish_accepted
      @user = User.find(params[:user_id])
      message = nil
      if params[:interaction_ids].blank?
        message = "Please select some interactions to publish."
      else
      params[:interaction_ids].each{|interaction_id|
        interaction = Interaction.find(interaction_id)
        authorize interaction, :revision_accepted?
        if interaction.update(revision: "published", published: true)
          interaction.save
        else
          message = "Something was not ok with the interactions, please check those in detail, that are not published."
        end
      }
      end
      redirect_to interactions_user_path(@user), notice: message || "All interactions have been published"
    end

    def update_reviewers
      @user = User.find(params[:user_id])
      authorize @user, :admin_tasks
      message = nil
      a=[]

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/views/interactions/search/_binding_to_adv_search.html.erb
  <div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
      <%= label_tag 'kaAdvSearch',"<i>K</i><sub>a</sub>".html_safe, class: "alignLabel" %>
    </div>
    <div class="col-md-4">
     <%= text_field_tag :binding_param, params[:binding_param], placeholder: "from", autofocus: true, class: "form-control search-box searchfield", id: 'ka' , onchange:"calculatetolog()" %>
   </div>
   <div class="col-md-4">
     <%= text_field_tag :binding_to_param, params[:binding_to_param], placeholder: "to", autofocus: true, class: "form-control search-box  searchfield", id: 'ka_upper' , onchange:"calculatetolog_upper()" %>
   </div>
 </div>
 <div class="form-group row">
   <div class="col-md-3" style="text-align:left;">
     <%= label_tag 'logKaAdvSearch',"log <i>K</i><sub>a</sub>".html_safe,  class: "alignLabel" %>
   </div>
   <div class="col-md-4">
     <%= text_field_tag :logka,nil, placeholder: "from", autofocus: true, class: "form-control search-box searchfield" , id:'logka', onchange:"calculatetodec()"%>
   </div>
  <div class="col-md-4">
    <%= text_field_tag :logka_upper, nil, placeholder: "to", autofocus: true, class: "form-control search-box searchfield", id:'logka_upper', onchange:"calculatetodec_upper()" %>
  </div>
</div>

app/views/interactions/search/_citation_adv_search.html.erb
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'doiAdvSearch',"DOI".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-8">
      <%= text_field_tag :doi_param, params[:doi_param], placeholder: "DOI", autofocus: true, class: "form-control search-box searchfield" %>
    </div>
</div>
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'authorAdvSearch',"Author".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-8">
      <%= text_field_tag :author_param, params[:author_param], placeholder: "Author", autofocus: true, class: "form-control search-box searchfield" %>
    </div>
</div>
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'yearAdvSearch',"Year".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-8">
      <%= text_field_tag :year_param, params[:year_param], placeholder: "Year", autofocus: true, class: "form-control search-box searchfield" %>
    </div>
</div>

app/views/interactions/search/_condition_adv_search.html.erb
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'solventAdvSearch',"Solvent".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-9">
      <%= text_field_tag :solvent_param, params[:solvent_param], placeholder: "solvent", autofocus: true, class: "form-control search-box  searchfield" , data: {autocomplete_source: query_solvents_path} %>
    </div>
</div>
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'bufferAdvSearch',"Buffer".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-9">
      <%= text_field_tag :buffer_param, params[:buffer_param], placeholder: "buffer", autofocus: true, class: "form-control search-box searchfield" %>
    </div>
</div>
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'pHAdvSearch',"pH".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-5">
      <%= text_field_tag :pH_param, params[:pH_param], placeholder: "from".html_safe, autofocus: true, class: "form-control search-box searchfield" %>
    </div>

   <div class="col-md-4">
     <%= text_field_tag :pH_to_param, params[:pH_to_param], placeholder: "to", autofocus: true, class: "form-control search-box searchfield" %>
   </div>
</div>
<div class="form-group row">
    <div class="col-md-3" style="text-align:left;">
       <%= label_tag 'tempAdvSearch',"Temperature".html_safe,  class: "alignLabel" %>
    </div>
    <div class="col-md-5">
      <%= text_field_tag :temperature_param, params[:temperature_param], placeholder: "in °C: &nbsp;&nbsp;from".html_safe, autofocus: true, class: "form-control search-box searchfield" %>
    </div>

   <div class="col-md-4">
     <%= text_field_tag :temperature_to_param, params[:temperature_to_param], placeholder: "to", autofocus: true, class: "form-control search-box searchfield" %>
   </div>
</div>

app/views/interactions/search/_method_adv_search.html.erb
<div class="form-group row">
   <div class="col-md-3" style="text-align:left;">
      <%= label_tag 'assayAdvSearch',"Assay".html_safe,  class: "alignLabel" %>
   </div>
   <div class="col-md-9">
      <%= text_field_tag :assay_type_param, params[:assay_type_param], placeholder: "DBA, CBA, ABA", autofocus: true, class: "form-control search-box searchfield", data: {autocomplete_source: query_assay_type_interactions_path } %>
   </div>
</div>
<div class="form-group row">
   <div class="col-md-3" style="text-align:left;">
     <%= label_tag 'techniqueAdvSearch',"Technique".html_safe,  class: "alignLabel" %>
   </div>
   <div class="col-md-9">
     <%= text_field_tag :technique_param, params[:technique_param], placeholder: "NMR, FL, ITC ...", autofocus: true, class: "form-control search-box searchfield", data: {autocomplete_source: query_technique_interactions_path }  %>
   </div>
</div>